# Generated by Django 5.2.11 on 2026-03-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_application_cover_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
